logging.level.root=INFO
logging.level.org.example=INFO
logging.level.org.springframework.web=WARN
logging.level.org.springframework.security=WARN
logging.level.org.hibernate.tool.schema=WARN

spring.jpa.show-sql=false

management.endpoint.health.show-details=when-authorized
